"""
Image Optimization
==================

CONCEPTS:
  1. Base image selection: alpine vs slim vs full
  2. Reduce image size: combine RUN layers, remove caches
  3. .dockerignore: exclude venv, __pycache__, .git
  4. ARG vs ENV: build-time vs runtime variables

NEW FILES THIS SESSION:
  Dockerfile.slim       — single-stage, slim base (~250MB)
  Dockerfile.alpine     — alpine multi-stage (~100MB, caveats)
  Dockerfile.buildargs  — ARG and ENV comprehensive demo
  app/requirements.alpine.txt — no C-extension deps (for alpine compat)

--- BASE IMAGE SELECTION ---

Base images come in three tiers for most languages:

  Tag             Approx Size   Base OS          Notes
  ─────────────── ───────────── ──────────────── ─────────────────────────────
  python:3.12     ~900MB        Debian (full)    Everything installed; build
                                                 tools, pip, gcc — safe but fat
  python:3.12-slim ~130MB       Debian (minimal) Just Python runtime; no build
                                                 tools. Needs gcc installed via
                                                 apt if a dep has C extensions
  python:3.12-alpine ~50MB      Alpine Linux     musl libc — C-extension wheels
                                                 must compile from source; pain
                                                 with psycopg2, cryptography,
                                                 numpy

After adding app code and packages, expected final image sizes:
  fastapi-single   ~1.0 GB   Dockerfile.single  (full base, single-stage)
  fastapi-slim     ~250 MB   Dockerfile.slim    (slim base, single-stage)
  fastapi-multi    ~200 MB   Dockerfile         (slim base, multi-stage)
  fastapi-alpine   ~100 MB   Dockerfile.alpine  (alpine base, multi-stage)

ALPINE GOTCHA — musl vs glibc:
  Most Python binary wheels are built for glibc (the manylinux standard).
  Alpine uses musl libc. pip can't use those prebuilt wheels on Alpine and
  must compile from source — which requires gcc, musl-dev, etc.

  Result: to get the smallest image, you often have to install a compiler,
  making your build MORE complex, not less. For any app with C-extension
  deps (psycopg2, cryptography, Pillow, numpy), start from slim, not alpine.

RECOMMENDATION:
  python:3.12-slim  for most production Python services
  python:3.12-alpine only if you can verify all deps are pure Python
  python:3.12       only in builder stages or local dev images

--- LAYER COMBINING: WHY IT MATTERS ---

Docker snapshots each layer independently. Even if a later layer deletes
files, those bytes are still in the earlier layer — Docker can't undo them.

WRONG — apt cache survives in layer 2 even though layer 3 cleans it:
  RUN apt-get update                # layer 1: fetches package list
  RUN apt-get install -y gcc        # layer 2: installs + stores cache
  RUN rm -rf /var/lib/apt/lists/*   # layer 3: deletes cache... from layer 3.
                                    # layers 1 and 2 still have it.

RIGHT — cleanup happens inside the same layer, so it's never committed:
  RUN apt-get update && \\
      apt-get install -y gcc && \\
      rm -rf /var/lib/apt/lists/*   # same layer: cache is never in the image

Same principle for pip:
  --no-cache-dir   prevents pip's download cache from being written at all
  This is better than writing it and then deleting it (which leaves it in a
  prior layer).

Rule: install and clean in the same RUN. Use \\ for multi-line readability.

--- .DOCKERIGNORE ---

Docker sends your entire build context (the directory you pass to build) to
the daemon before it executes any Dockerfile instruction. This happens every
build, even before FROM runs.

Excluding large or irrelevant directories speeds up every build and prevents
accidental cache busts (if Docker sees a changed file in the context, it may
invalidate layers even if that file isn't COPYed).

What to always exclude:
  .git/         — your entire git history (can be hundreds of MB)
  .venv/ venv/  — local virtualenv (never needed in an image)
  __pycache__/  — compiled bytecode (regenerated by Python anyway)
  *.pyc *.pyo   — individual bytecache files
  .env          — local env file (never bake secrets into images)
  *.md          — docs
  notes*.py     — practice scripts not needed in the image

The syntax is identical to .gitignore.

--- ARG vs ENV ---

  Feature              ARG (build-time)        ENV (runtime)
  ─────────────────── ──────────────────────── ─────────────────────────────
  When available      Only during `docker build` During build AND at runtime
  In running container No                      Yes
  Override mechanism  --build-arg at build time -e flag at `docker run` time
  Visible in history  Yes (docker history)     Yes
  Safe for secrets    NO                       NO (use secrets/mounts instead)

Common pattern — use ARG to set a default, ENV to propagate it to runtime:
  ARG PORT=8000        ← build-time default
  ENV PORT=${PORT}     ← bakes it into the image as a runtime variable

The running container can still be overridden:
  docker run -e PORT=9001 myimage   ← replaces ENV at runtime

Python ENV vars to set in every image:
  PYTHONDONTWRITEBYTECODE=1   no .pyc files written to disk
  PYTHONUNBUFFERED=1          logs appear immediately in docker logs
  PYTHONFAULTHANDLER=1        better crash tracebacks

--- COMMANDS TO RUN ---

# Build all four variants
docker build -f Dockerfile.single -t fastapi-single .
docker build -f Dockerfile.slim   -t fastapi-slim   .
docker build -t fastapi-multi .
docker build -f Dockerfile.alpine -t fastapi-alpine .

# Compare sizes side by side
docker images | grep fastapi

# Build with custom ARG values
docker build -f Dockerfile.buildargs --build-arg PORT=9000 --build-arg APP_ENV=development -t fastapi-buildargs .

# Run the buildargs image on port 9000
docker run -p 9000:9000 fastapi-buildargs
curl http://localhost:9000

# Override ENV at runtime (regardless of what ARG/ENV said at build time)
docker run -p 8000:8000 -e PORT=8000 fastapi-buildargs

# Inspect what ARG values were baked in (they appear in history)
docker history fastapi-buildargs

# See layers and their sizes for each image
docker history --no-trunc fastapi-single | head -20
docker history --no-trunc fastapi-multi  | head -20

# Confirm the alpine image has no pip at runtime
docker run --entrypoint sh -it fastapi-alpine -c "which pip; echo exit: $?"

# Check that PYTHONUNBUFFERED is set in the buildargs image
docker run --entrypoint sh fastapi-buildargs -c "echo $PYTHONUNBUFFERED"

--- LAYER COMBINING EXERCISE ---

To SEE layers and their individual sizes:
  docker history fastapi-single

Notice layers with "(missing)" — that's normal for base image layers pulled
from a registry; their content is stored but the build context isn't local.
The layers you added (pip install, COPY) will show their sizes clearly.

Try this experiment:
  1. Add a large dummy file inside a RUN in Dockerfile.slim:
       RUN dd if=/dev/urandom of=/tmp/bigfile bs=1M count=100 && rm /tmp/bigfile
  2. Build and check: docker history fastapi-slim
  3. The 100MB is STILL IN THE IMAGE even though it was deleted.
  4. Move the rm into the same RUN:
       RUN dd ... && rm /tmp/bigfile
  5. Rebuild — now that layer is nearly zero bytes.
"""


BASE_IMAGE_SIZES = {
    "python:3.12":        "~900MB",
    "python:3.12-slim":   "~130MB",
    "python:3.12-alpine": "~50MB",
}

FINAL_IMAGE_SIZES = {
    "fastapi-single  (Dockerfile.single)":  "~1.0 GB",
    "fastapi-slim    (Dockerfile.slim)":    "~250 MB",
    "fastapi-multi   (Dockerfile)":         "~200 MB",
    "fastapi-alpine  (Dockerfile.alpine)":  "~100 MB",
}


def print_size_comparison():
    print("Base image sizes:")
    for image, size in BASE_IMAGE_SIZES.items():
        print(f"  {image:<25} {size}")
    print()
    print("Final app image sizes (after adding FastAPI + deps):")
    for image, size in FINAL_IMAGE_SIZES.items():
        print(f"  {image:<45} {size}")
    print()
    print("Run 'docker images | grep fastapi' to see your actual numbers.")


def print_run_layer_exercise():
    print("Layer combining exercise:")
    print("  Add to Dockerfile.slim:")
    print("    BAD:  RUN dd if=/dev/urandom of=/tmp/big bs=1M count=50")
    print("          RUN rm /tmp/big")
    print("    GOOD: RUN dd if=/dev/urandom of=/tmp/big bs=1M count=50 && rm /tmp/big")
    print()
    print("  Build both variants, then:")
    print("    docker history fastapi-slim")
    print("  BAD version: 50MB layer still in image even after deletion.")
    print("  GOOD version: layer is ~0 bytes.")


if __name__ == "__main__":
    print_size_comparison()
    print()
    print_run_layer_exercise()
