"""add is_admin to user

Revision ID: 259e700a3fc8
Revises: 45877fa6978b
Create Date: 2026-05-16 18:36:33.150447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "259e700a3fc8"
down_revision: Union[str, Sequence[str], None] = "45877fa6978b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add as nullable so the ALTER doesn't lock the table or fail
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=True))
    # 2. Backfill existing rows
    op.execute('UPDATE "user" SET is_admin = false')
    # 3. Now it's safe to make NOT NULL
    op.alter_column("user", "is_admin", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###
