"""add first and last name to user

Revision ID: 7940bfdb5570
Revises: 1503cb4cee63
Create Date: 2026-05-17 19:52:02.720525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7940bfdb5570"
down_revision: Union[str, Sequence[str], None] = "1503cb4cee63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
    )
    op.execute("UPDATE \"user\" SET first_name = username, last_name = ''")
    op.alter_column("user", "first_name", nullable=False)
    op.alter_column("user", "last_name", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###
