"""add default category to user

Revision ID: 893690c2c502
Revises: 7940bfdb5570
Create Date: 2026-05-19 07:58:30.290562

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "893690c2c502"
down_revision: Union[str, Sequence[str], None] = "7940bfdb5570"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("default_category_id", sa.Integer(), nullable=True))
    op.execute(
        'UPDATE "user" SET default_category_id = (SELECT id FROM category WHERE user_id = "user".id ORDER BY created_at ASC LIMIT 1)'
    )
    op.create_foreign_key(
        "fk_user_default_category_id",
        "user",
        "category",
        ["default_category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_default_category_id", "user", type_="foreignkey")
    op.drop_column("user", "default_category_id")
    # ### end Alembic commands ###
