"""set bookmark category_id to cascading delete

Revision ID: d126a395ad92
Revises: 893690c2c502
Create Date: 2026-05-19 10:03:24.830237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d126a395ad92"
down_revision: Union[str, Sequence[str], None] = "893690c2c502"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("bookmark_category_id_fkey"), "bookmark", type_="foreignkey"
    )
    op.create_foreign_key(
        "bookmark_category_id_fkey",
        "bookmark",
        "category",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bookmark_category_id_fkey", "bookmark", type_="foreignkey")
    op.create_foreign_key(
        op.f("bookmark_category_id_fkey"),
        "bookmark",
        "category",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
